// Privacy Policy and Terms of Use. Plain-language templates -- have them reviewed before charging money.
const UPDATED = "September 28, 2026";
const CONTACT_EMAIL = "jobrandes+zerotoemt@gmail.com"; // set to a public contact address to show it on both pages

const Section = ({ title, children }) => (
  <section className="zte-legal-section">
    <h2 className="zte-legal-h2">{title}</h2>
    {children}
  </section>
);

export default function Legal({ page, onBack, onSwitch }) {
  const isPrivacy = page === "privacy";
  return (
    <div id="zte-root">
      <nav className="zte-nav">
        <button className="zte-logo" onClick={onBack}>ZERO <span>TO</span> EMT</button>
        <button className="zte-btn-signout" onClick={onBack}>Back</button>
      </nav>
      <main className="zte-legal">
        <div className="zte-tagline-mono">LEGAL</div>
        <h1 className="zte-legal-h1">{isPrivacy ? "PRIVACY POLICY" : "TERMS OF USE"}</h1>
        <p className="zte-legal-meta">Last updated {UPDATED}</p>

        {isPrivacy ? (
          <>
            <Section title="What we collect">
              <p>When you create an account we collect your first name, email address and password (stored securely by our sign-in provider, never in plain text). As you learn, we store your progress: which lessons you finished and your quiz scores. If you use the AI Tutor, we process the messages you type. If you send us feedback, we store what you write.</p>
            </Section>
            <Section title="What we do with it">
              <p>We use your information only to run the app: sign you in, save and sync your progress across devices, answer your questions in the AI Tutor, and improve the lessons. We do not sell your personal information and we do not show ads.</p>
            </Section>
            <Section title="Who processes your data">
              <p>We rely on a few service providers. Supabase stores your account and progress. Netlify hosts the site and runs our server functions. Anthropic provides the AI behind the Tutor: the text of your Tutor messages, along with the lesson you are studying, is sent to Anthropic to generate a reply. Please do not type sensitive personal information, health details about yourself or others, or anything identifying a real patient into the Tutor.</p>
            </Section>
            <Section title="Your choices">
              <p>You can delete your account at any time from the Account menu in the app. Deleting your account permanently removes your sign-in, progress and scores from our systems. Some copies may remain briefly in provider backups before they are overwritten.</p>
            </Section>
            <Section title="How long we keep it">
              <p>We keep your information while your account is open. When you delete your account, we delete it as described above.</p>
            </Section>
            <Section title="Children">
              <p>Zero to EMT is intended for adults and older teens preparing for EMT training. It is not directed to children under 13, and we do not knowingly collect information from them.</p>
            </Section>
            <Section title="Security">
              <p>We use reputable providers and encrypted connections, but no system is perfectly secure. Use a strong, unique password.</p>
            </Section>
            <Section title="Changes">
              <p>If we change this policy we will update the date above. If the changes are significant we will tell you in the app.</p>
            </Section>
          </>
        ) : (
          <>
            <Section title="Educational use only">
              <p>Zero to EMT is a study aid. It is not medical advice, clinical guidance, or a substitute for an accredited EMT course, your instructor, your medical director, or your local protocols. Never use this app to make decisions about real patient care. In an emergency, call your local emergency number.</p>
            </Section>
            <Section title="No affiliation, no guarantees">
              <p>Zero to EMT is not affiliated with, endorsed by, or approved by the National Registry of Emergency Medical Technicians (NREMT) or any state EMS agency. We work to keep content accurate and current, but protocols and exam blueprints change and errors can happen. We do not guarantee that using the app will help you pass any course or exam.</p>
            </Section>
            <Section title="The AI Tutor">
              <p>The AI Tutor is generated by an AI model and can be wrong. Check anything important against your course materials and instructor.</p>
            </Section>
            <Section title="Your account">
              <p>You are responsible for keeping your login secure and for activity on your account. Provide accurate information and do not share your account. You must be at least 13 years old to use the app.</p>
            </Section>
            <Section title="Acceptable use">
              <p>Do not misuse the app: no attempts to break or overload it, no scraping or copying the lessons and question banks for redistribution, and no using the Tutor to produce harmful or unlawful content.</p>
            </Section>
            <Section title="Content">
              <p>The lessons, questions and design are owned by Zero to EMT. You may use them for your own personal study.</p>
            </Section>
            <Section title="Availability and changes">
              <p>The app is provided as is, without warranties of any kind, and may change or be unavailable from time to time. To the fullest extent permitted by law, we are not liable for indirect or consequential losses arising from your use of the app. We may update these terms; continuing to use the app after an update means you accept the new terms.</p>
            </Section>
            <Section title="Ending your use">
              <p>You can stop using the app and delete your account at any time from the Account menu. We may suspend accounts that break these terms.</p>
            </Section>
          </>
        )}

        {CONTACT_EMAIL && <p className="zte-legal-contact">Questions? Contact us at {CONTACT_EMAIL}.</p>}
        <button className="zte-legal-switch" onClick={() => onSwitch(isPrivacy ? "terms" : "privacy")}>
          {isPrivacy ? "Read the Terms of Use" : "Read the Privacy Policy"} &rarr;
        </button>
      </main>
    </div>
  );
}
